### ISSUE TITLE
Install Failed: Not Found

### ISSUE THREAD

**Issue by Ironxxx** [rockshow888/health-monitor#1]
When trying to install this on Foundry 0.6 I get "Install Failed: Not Found" when using the manifest link
https://raw.githubusercontent.com/rockshow888/health-monitor/master/module.json
as shown in Foundry discord
I'm using Chrome, Windows 10.

**Comment by rockshow888** [comment]
It works fine for me.
Try to install manually, download the .zip file and extract it in FVTT installation folder\world\Data\modules

**Comment by Ironxxx** [comment]
Using the Health-Monitor zip within the Health-Monitor-Master Zip worked great, thanks. The master zip didn't work, dunno if it was meant to.

Thanks for the help, the mod is great
