### ISSUE TITLE
When "Token Configuration", "Character" tab has "Display Name" set to "Hovered by Owner" (and owner is GM), the actor's name is being displayed to players (who don't own the character).

### ISSUE THREAD

**Issue by adventuremagic123** [rockshow888/health-monitor#12]
This module is revealing character names to my players, who should not be able to see those names.  Please add a feature to honor the settings in the Token Configuration.

BTW, this module is invaluable to me.  Occasionally, I've got the wrong tokens selected when I apply healing or damage -- and this module helps me detect that and fix it quick.  Also, it prevents players from cheating.  In addition, it provides a good audit trail.

**Comment by rockshow888** [comment]
Works as intended.
